### ISSUE TITLE
single command duration

### ISSUE THREAD

**Issue by mariodeci** [vmi/selenese-runner-java#143]
Hi,

Is possible to have, in the report, the duration (time in ms) of each executed command?

**Comment by vmi** [comment]
I pushed "each-command-duration-143" branch for this issue.
https://github.com/vmi/selenese-runner-java/tree/each-command-duration-143

note: It is experimental.

**Comment by vmi** [comment]
Thank you for waiting.
I added each command duration to HTML result.
Please add comment to #154 if you want to change the feature.

> Others Suggestions: 
> -write statistics (test_id, steps, tot_time, single_step_time, steps_status) on csv/xls for example (or on remote JMS queue or something else)

It is a good idea. I opend new issue #155.

> -documentation for use this project as a library

I will consider it. Please wait.

> -the status of the machine (based on ram, cpu, browsers,..): something like an alghoritm to calculate for example the initial max_sessions suggested for the machine, or the current state needed to start "another test" on same machine (based on number of browsers instances currently running) 

Hmmm, I can't imagine it materially.

> -a scheduler to start scheduled test (but it's already simple to implement with external library)

I think it's better to use CI tools like Jenkins.

**Comment by vmi** [comment]
Can I close this ticket?
Please provide addtional information if have some request.
