### ISSUE TITLE
Selenese "type" command not working with most recent Firefox version 35

### ISSUE THREAD

**Issue by amirjamak** [vmi/selenese-runner-java#150]
As stated in the title, after upgrading the firefox to 35 "type" command no longer works.

**Comment by vmi** [comment]
Oh, Selenium is broken on Firefox35...
e.g. Issue 8390: Firefox 35: Passing arguments to executeScript isn't working
https://code.google.com/p/selenium/issues/detail?id=8390

**Comment by vmi** [comment]
I think we have no choice but to wait Selenium to be fixed.

**Comment by vmi** [comment]
Selenium 2.45.0 is back to normal on Firefox.
"type" command works on firefox 35.
Please check it.

**Comment by amirjamak** [comment]
OK, let me check and update.

**Comment by amirjamak** [comment]
Looks like it works now with FF35. I am closing this issue. Thanks!
