### ISSUE TITLE
Browser Caching

### ISSUE THREAD

**Issue by mariodeci** [vmi/selenese-runner-java#152]
Now all testsuites/testcases are without cache, right?

Is possible to introduce a "cache" config param to use a browser cache in a testcase/testsuite and between different testsuite?

**Comment by vmi** [comment]
I think it is not possible.

Selenium WebDriver has no common interface for browser cache,
and it depends on each WebDriver implementation.
e.g. FirefoxDriver creates new temporary profile directory which has disk cache at starting.
I think that disk cache seems cleared at each exection.

**Comment by mariodeci** [comment]
For firefox a good idea should be a fixed path for the profile, I think. Using same profile and enabling cache in capabilities, should be ok.

I will test it

**Comment by xmhubj** [comment]
cache is enabled by default. As vmi mentioned, disk cache/temporary profile directory are cleared after each test execution. You need to consider the cache may break tests, when you run testcase/testsuite which has login page. The cache of previous test "dirties" the following tests
