### ISSUE TITLE
Error during execution with --html-result

### ISSUE THREAD

**Issue by asherbitton** [vmi/selenese-runner-java#158]
Hi,

Running a test with this option we got an error of:
IndexOutOfBoundsException: Index: 0, Size: 0' can not be accessed: "java.lang.NoSuchFieldException: resultList"!
Looking at the template file result.html (located at:"src\main\resources\jp\vmi\html\result\result.html") it seems it refers to a selenese attribute\property resultList which does not exist in the class\interface (or anywhere else, I only found cresultList in the TestCase class).
Obviously removing the offending piece in the template makes the process work properly, question is what was lost while doing this ...

I'd be happy to get a  proper fix for this.

Thanks,
Asher

**Comment by vmi** [comment]
Hi,

I fixed it.
But I have no test case, please test it.

**Comment by vmi** [comment]
Can I close this ticket?
