### ISSUE TITLE
storeEval on remote Firefox hangs forever

### ISSUE THREAD

**Issue by mhlz** [vmi/selenese-runner-java#161]
As the title says. I'm trying to use JQuery to click on a button that may or may not be there:

```
<tr>
     <td>storeEval</td>
     <td>window.$("div#id form div a span").click();</td>
     <td></td>
</tr>
```

It works fine in the Selenium IDE, but when I execute this test case with Selenese Runner using a grid server and Firefox, the execution just stops there. The button does not get clicked and the runner just hangs.

If you need more information I'd be happy to give it to you. I'd also appreciate workarounds for the mean time. Is there a way I can click on a button and have the test case not fail if the button isn't there/visible?

**Comment by vmi** [comment]
Hi,

I tried to reproduce your problem, but I failed.

1. Put the following HTML to Web server:  
https://github.com/vmi/selenese-runner-java/blob/master/src/test/resources/htdocs/jquery.html
2. Create the following script:  
https://github.com/vmi/selenese-runner-java/blob/master/src/test/resources/selenese/jqueryTest.html
3. Run `java -jar selenium-server-standalone-2.46.0.jar`.
4. Run `java -jar selenese-runner.jar -d remote --remote-url http://localhost:4444/wd/hub --remote-browser firefox src/test/resources/selenese/jqueryTest.html`.
5. It terminated normally.

Please provide how to reproduce your problem.

**Comment by vmi** [comment]
Hi,

Please provide addtional information.

**Comment by vmi** [comment]
Hi,
I will close this issue if you don't provide information above-mentioned.
