### ISSUE TITLE
verify table cell fails in selenese-runner, works in IDE

### ISSUE THREAD

**Issue by katii** [vmi/selenese-runner-java#163]
Hi, 

First of all thank you for the selenese-runner. It works so much better than selenium standalone server I've used before!

However... I recorded a test case with Selenium IDE having these verifications:
[info] Executing: |verifyText | //tr[contains(td[1], "selenium_testi")]/td[2] | selenium testi FIN |
[info] Executing: |verifyText | //tr[contains(td[1], "selenium_testi")]/td[3] | *selenium testi ENG | 

Both verifications pass in IDE (as you can see above log lines) but the latter one fails in selenese-runner:
verifyText	//tr[contains(td[1], "selenium_testi")]/td[2]	selenium testi FIN	[Success]	
verifyText	//tr[contains(td[1], "selenium_testi")]/td[3]	*selenium testi ENG	[Warning: Assertion failed (Result: [*selenium testi ENG] / Expected: [*selenium testi ENG])]	

It seems as I tested it that the asterisk * in front of the expected value makes the verification fail.

Selenese Runner Version:	1.11.0
WebDriver Name:	FirefoxDriver
Selenium Version:	2.46.0
Java Version:	1.8.0_45
Java VM Name:	Java HotSpot(TM) 64-Bit Server VM
Operating System:	Windows 8.1 6.3 (amd64)

**Comment by vmi** [comment]
I fixed the bug.
Please test it.

**Comment by vmi** [comment]
Can I close this ticket?
