### ISSUE TITLE
supported command gotolabel should be gotoLabel

### ISSUE THREAD

**Issue by AndreaColoru** [vmi/selenese-runner-java#169]
Hi
I think that there is a mismatch between the case of the command gotoLabel. The problem is that in sideflow the command is declared as gotoLabel (tested within selenium IDE) but in Selenese runner I got an exception since the command is not recognized.
Actually the command in Selenese runner exist as gotolabel instead gotoLabel.
Thanks in advance.
Best regards.

**Comment by vmi** [comment]
Hi,

I added command "gotoLabel" which is same as "gotolabel".
Please test it.

**Comment by vmi** [comment]
Please re-open this if there is still any problem.
