### ISSUE TITLE
add properties to JUnitXML. OS,Browser,baseuri,etc....

### ISSUE THREAD

**Issue by hayato1980** [vmi/selenese-runner-java#17]

**Comment by vmi** [comment]
I added the following properties to JUnit testsuite xml:

    <properties>
        <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
        <property name="java.version" value="1.8.0_77"/>
        <property name="os.name" value="Mac OS X"/>
        <property name="os.version" value="10.11.4"/>
        <property name="os.arch" value="x86_64"/>
        <property name="user.language" value="ja"/>
        <property name="user.country" value="JP"/>
        <property name="user.timezone" value="Asia/Tokyo"/>
        <property name="seleneseRunner.args" value="'--config' 'tools/run.config' 'src/test/resources/selenese/testcase_issue195.html'"/>
        <property name="seleneseRunner.version" value="2.6.1-SNAPSHOT"/>
        <property name="selenium.version" value="2.53.0"/>
        <property name="selenium.webDriver.name" value="FirefoxDriver"/>
    </properties>
