### ISSUE TITLE
--cli-args Fails with Exit code: 1

### ISSUE THREAD

**Issue by Harinus** [vmi/selenese-runner-java#171]
When I use "--cli-args -private-window about:blank" Selenese fails with exit code 1.
"--cli-args about:blank" works fine.

**Comment by vmi** [comment]
Hi,

One "--cli-args" takes one argument only.
If you want to pass multiple cli arguments, you can specify as follows:

    --cli-args -private-window --cli-args about:blank

**Comment by Harinus** [comment]
Hi,

splitting into multiple still fails: The "-" at the beginning seems to be the issue. But it is required on every Argument by firefox.. except the URL

**Comment by vmi** [comment]
Hmmm.
It may be a bug.
I will analyze it.
Please tell me your all command line parameters.

**Comment by vmi** [comment]
It is the bug, but it is caused by the specification of the dependence library (commons-cli).
Please wait a moment.

**Comment by Harinus** [comment]
Found a workaround (for Windows): --cli-args /private-window --cli-args about:blank
Notice the "-" replaced by "/". The bug should be fixed anyways.

**Comment by vmi** [comment]
I replaced command line parser library to fix this problem.
Please check `issue171`  branch.

**Comment by Harinus** [comment]
The `issue171` branch fixes the error.
