### ISSUE TITLE
Problem with Proxy

### ISSUE THREAD

**Issue by Harinus** [vmi/selenese-runner-java#172]
Hi, 

I am having trouble with the Proxy settings:
my command:
```
java -jar C:\Users\xyz\Desktop\selenese-runner.jar --strict-exit-code --proxy localhost:8080 --screenshot-on-fail C:\Users\xyz\Desktop\screens --set-speed 3000 --cli-args about:blank C:\Users\xyz\Desktop\ipw-test.html
```

The requests get proxied through my localhost proxy as they should. However, i still get a prompt for another authenticated Proxy which is set in IE (Auto Configuration) which i dont want to use for selenese. I have to cancel it manually, that the script starts with the regular procedure.

I found out that it is caused by the mozilla services which make some automatic requests to the internet. I would expect those requests to be proxied through localhost aswell and then time out due to missing access. 

Best regards,
Martin

**Comment by Harinus** [comment]
I analyzed this issue and found out that its not directly caused by your components but Selenium itself:
See the issue i opened: https://github.com/SeleniumHQ/selenium/issues/1326

In conclusion it might be a good idea to directly set the Proxy in the Profile.
If there was no Profile specified via commandline you can assume that a new one gets created, so no conflicts. If there is a command line option for a profile the issue is unlikely to occur because the user will have set the correct proxy already.

**Comment by vmi** [comment]
Thanks your information!

**Comment by Harinus** [comment]
PR tested and confirmed as working! I will keep you up to date when Selenium fixes the root cause of the issue. Thanks for the quick fix.
