### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by cancetin1** [vmi/selenese-runner-java#178]
Could not initialize class java.lang.UNIXProces this comes when i try to process with the source code. how to fix it ?

**Comment by vmi** [comment]
Hi,

Hmmm, I cannot understand your problem.
Please provide more information.

* What is your purpose?
* What is your environment? (such as OS/tools name, version)
* What operation did you perform? (such as command line, source code)
* What result did you expect?
* What result did you get actually? (such as error message, stack trace)

**Comment by vmi** [comment]
Hi,
I will close this issue if you don't provide information above-mentioned.
