### ISSUE TITLE
pageLoadTimeout did not work via selenese-runner-java

### ISSUE THREAD

**Issue by leoforever** [vmi/selenese-runner-java#190]
when i set driver.pageLoadTimeout and get url via selenium directly, the page loading process can stop when timeout.
but when i use selenese-runner-java , i find even i set the driver.pageLoadTimeout ,the page loading will not stop when timeout.  although when  finish eventually , it will rise up a timeout exception , but it will cost too much time. Also run.settimeout does not work at this problem.

**Comment by vmi** [comment]
Hi,
I added initialization of pageLoadTimeout at Runner#setTimeout and Runner#setDriver.
And I released 2.6.0.
Please test it.

**Comment by vmi** [comment]
Hi,
Can I close this issue?
