### ISSUE TITLE
White space issue

### ISSUE THREAD

**Issue by asherbitton** [vmi/selenese-runner-java#191]
The following step in a test case that works in selenium IDE:
<tr>
	<td>assertText</td>
	<td>css=#initialLoadOptionTitleRow > td.row</td>
	<td>Enter Amount (US$) to Load (Enter US $20.00 or more)</td>
</tr>
The value in the page has to leading spaces (&nbsp) and it seems the IDE ignores them (properly? selenium says that on XPath hey do NOT trim whites-paces, but I might be wrong)).
When executed via the selenese runner the assert fails, failing due to the two leading spaces.
We are attempting to work around this by using a different selector:
//tr[@id='initialLoadOptionTitleRow']/td[normalize-space(text())]
However we would really like it to work without the workaround.

**Comment by vmi** [comment]
Hi,
I fixed this problem and released 2.6.0.
Please test it.

**Comment by asherbitton** [comment]
Thanks, problem resolved.
