### ISSUE TITLE
BR not identified

### ISSUE THREAD

**Issue by asherbitton** [vmi/selenese-runner-java#195]
A test step was recorded in the IDE as:
<tr>
	<td>assertText</td>
	<td>id=panel_form</td>
	<td>Choose one:**<br />**US Social Security Number Passport Number US Driver License Matricula Consular</td>
</tr>

The above works in the IDE however fails on the runner, output on runner is:
              <tr class="cmd_status_failure">
                  <td class="index">33</td>
      
                  <td>assertText</td>
      
                  <td>id=panel_form</td>
      
                  <td>Choose one:**<br>
**US Social Security Number Passport Number US Driver License Matricula Consular</td>
      
                  <td class="number">750</td>
                  <td></td>
                </tr> 

If it helps, the HTML from which the test step was recorded is:
<br>
Choose one:<br>
<table height="10" width="450" border="0" cellpadding="0" cellspacing="0">
<tbody><tr valign="bottom">
<td class="row"> <select id="DocTypeId" name="DocTypeId" onchange="DocTypeSelector.setSelection(this.value)" class="tdrop" size="1" style="background-color:white;">
<option value="SSN" selected="">US Social Security Number</option>
<option value="PASS">Passport Number</option>
<option value="UDL">US Driver License</option>
<option value="MCN">Matricula Consular</option>
</select>
</td>
</tr>
</tbody></table>

**Comment by vmi** [comment]
Hi,

I fixed this problem, and released new version (2.7.0).
Please test it.

**Comment by vmi** [comment]
Hi,
Can I close this issue?

**Comment by vmi** [comment]
Please re-open this issue if your problem is not resolved.
