### ISSUE TITLE
waitForPageToLoad

### ISSUE THREAD

**Issue by DOCPROF** [vmi/selenese-runner-java#197]
"waitForPageToLoad" is useful to stop selenium IDE software testing tool's execution until page not get loaded successfully. In IDE it is not useful to specify a value in target column. Selenium IDE software testing tool will execute next command once page loaded. With selenese-runner-java, if there is no value in target column, we have this error : 
`[Error: NumberFormatException - For input string: "" (NumberFormatException.forInputString(NumberFormatException.java:65) / Long.parseLong(Long.java:453) / Long.parseLong(Long.java:483) / WaitForPageToLoad.handleSeleneseCommand(WaitForPageToLoad.java:54) / `

**Comment by vmi** [comment]
I fixed this issue and released new version (2.8.0).
Please test it.

**Comment by DOCPROF** [comment]
Ok It's good, thanks.
