### ISSUE TITLE
Question about the command duration

### ISSUE THREAD

**Issue by wangzhih** [vmi/selenese-runner-java#198]
How does the duration (StopWatch getDuration) of a "open" command calculated? What is its relationship to the onLoad page timing? thanks.

**Comment by vmi** [comment]
Hi,

I think that that's right.
`open` command waits until `WebDriver#get` method of Selenium WebDriver ends.
and the method waits until `document.readyState` is `complete`.

**Comment by wangzhih** [comment]
Thanks for the response. 

Then I have further question. I used BMP to get the HAR when playback the selenium script. What I found is that the startedDateTime of Page 0 and entry 0 are not the same, The startedDateTime of entry 0 is of several hundreds milliseconds later than the startedDateTime of the Page. How to explain this? 

Can this time difference affect the response time of opening a page by selenium? Are there any overhead of the response time captured by selenium vs. the response time captured by firebug? It seems the response time captured by selenium is bigger than the response time captured by firebug. Thanks.

**Comment by vmi** [comment]
The reasons are as follows:

* The timing the start time of the test case is recorded is different from the timing the start time of each command is recorded.
* Many overheads are included in processing of Selenese Runnner. The biggest one is communication with Selenium WebDriver and a browser.

Firebug has only little overheads except for processing of browser.
