### ISSUE TITLE
playback script to test answerOnNextPrompt & assertPrompt failed

### ISSUE THREAD

**Issue by wangzhih** [vmi/selenese-runner-java#203]
Related to #192, I tried the following script:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://www.w3schools.com/" />
<title>prompt</title>
</head>
<body>

<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">prompt</td></tr>
</thead><tbody>
<tr>
    <td>open</td>
    <td>/js/tryit.asp?filename=tryjs_prompt</td>
    <td></td>
</tr>
<tr>
    <td>click</td>
    <td>//button[@onclick='submitTryit()']</td>
    <td></td>
</tr>
<tr>
    <td>selectFrame</td>
    <td>iframeResult</td>
    <td></td>
</tr>
<tr>
    <td>answerOnNextPrompt</td>
    <td>test</td>
    <td></td>
</tr>
<tr>
    <td>click</td>
    <td>css=button</td>
    <td></td>
</tr>
<tr>
    <td>assertPrompt</td>
    <td>Please enter your name</td>
    <td></td>
</tr>
<tr>
    <td>verifyTextPresent</td>
    <td>test</td>
    <td></td>
</tr>
</tbody></table>

</body>
</html>

This is working fine on Selenium IDE but when I run it with selenese-runner-jar, it failed. BTW, my Firefox is of version v42.0.

c:> java -jar selenese-runner-java-2.8.0.jar c:\prompt1.html

[2016-07-07 13:03:38.665 +08:00] [INFO] <4> Command#4: answerOnNextPrompt("test"
)
[2016-07-07 13:03:38.712 +08:00] [INFO] - [Success]
[2016-07-07 13:03:38.713 +08:00] [INFO] <5> Command#5: click("css=button")
[2016-07-07 13:03:38.879 +08:00] [INFO] - [Success] No page information: [Unexpe
cted modal dialog (text: Please enter your name): Please enter your name]
[2016-07-07 13:03:38.879 +08:00] [INFO] <6> Command#6: assertPrompt("Please ente
r your name")
[2016-07-07 13:03:38.934 +08:00] [ERROR] Command#6: assertPrompt("Please enter y
our name") => [Error: SeleniumException - There were no prompts (DialogOverride.
getNextPrompt(DialogOverride.java:61) / GetPrompt.execute(GetPrompt.java:25) / G
etPrompt.execute(GetPrompt.java:9) / Assertion.executeImpl(Assertion.java:112) /
 AbstractCommand.execute(AbstractCommand.java:145) / CommandList.doCommand(Comma
ndList.java:97) / ScreenshotInterceptor.invoke(ScreenshotInterceptor.java:18) /
AbstractDoCommandInterceptor.invoke(AbstractDoCommandInterceptor.java:29) / High
lightInterceptor.invoke(HighlightInterceptor.java:28) / AbstractDoCommandInterce
ptor.invoke(AbstractDoCommandInterceptor.java:29) / CommandLogInterceptor.invoke
(CommandLogInterceptor.java:72) / AbstractDoCommandInterceptor.invoke(AbstractDo
CommandInterceptor.java:29) / CommandList.execute(CommandList.java:153) / TestCa
se.execute(TestCase.java:307) / ExecuteTestCaseInterceptor.invoke(ExecuteTestCas
eInterceptor.java:52) / AbstractExecuteTestCaseInterceptor.invoke(AbstractExecut
eTestCaseInterceptor.java:29) / TestSuite.execute(TestSuite.java:158) / ExecuteT
estSuiteInterceptor.invoke(ExecuteTestSuiteInterceptor.java:49) / AbstractExecut
eTestSuiteInterceptor.invoke(AbstractExecuteTestSuiteInterceptor.java:29) / Runn
er.execute(Runner.java:568) / Runner.run(Runner.java:612) / Main.run(Main.java:8
3) / Main.main(Main.java:213))] URL: [http://www.w3schools.com/js/tryit.asp?file
name=tryjs_prompt] / Title: [Tryit Editor v3.0]

Please advise if there is anything wrong for this test? Thanks.

**Comment by wangzhih** [comment]
May I know the target date of 2.10.0 milestone? Thanks a lot.

**Comment by vmi** [comment]
I will include the fix of this issue in the next release, but I don't have schedule of the target date yet.

**Comment by wangzhih** [comment]
thanks.

**Comment by vmi** [comment]
I fixed this issue on "issue203" branch.
However, I modified too many code, so I have not completed to make tests yet.
Please report if you find other problems.

**Comment by vmi** [comment]
Hi,

I released the new version 2.10.0 which fixes  this problem.
Please test it.

**Comment by vmi** [comment]
Please re-open this issue if your problem is not resolved.
