### ISSUE TITLE
assertConfirmation

### ISSUE THREAD

**Issue by schunt1** [vmi/selenese-runner-java#206]
I'm using assertConfirmation \* to click the OK on a javascript confirmation.  It works with selenium IDE and -htmlSuite but not with selenium-runner?

**Comment by schunt1** [comment]
If it helps, I can actually see the js confirmation display and instantly close.  The log shows the following:
Command#27: assertConfirmation("*") => [Error: SeleniumException - There were no confirmations (AlertOverride.getNextConfirmation(AlertOverride.java:154) / GetConfirmation.handleSeleneseCommand(GetConfirmation.java:33)

If I try a confirmPresent I get:
Command#28: assertConfirmationPresent() => [Failure: Assertion failed (Result: [false] / Expected: [true])]

This true of all my scripts with js alerts and confirmations.

Browser = firefox

**Comment by vmi** [comment]
Hi,

I released the new version 2.10.0 which fixes this problem.
Please test it.

**Comment by vmi** [comment]
Please re-open this issue if your problem is not resolved.
