### ISSUE TITLE
step-by-step and interactive execution mode

### ISSUE THREAD

**Issue by tgianko** [vmi/selenese-runner-java#210]
I am wondering if there's a way or any future plan to have a step-by-step, interactive way to run testcases. 

This is the problem I want to solve. After each step, (e.g., click, sendkeys, ...) I need to do few checks on the web application under test (none of which concerns selenese-runner). The important aspect here is that I need to do these checks after each single step. 

The first obvious solution for me is to run the test with a sufficiently low speed. The problem here is that I cannot make any assumption about the speed. In most cases, checks are fast and I spend time waiting for the timeout. If I make it fast, then checks are no longer in sync with the test execution. 

As an alternative solution, I thought that here it would help a sort of step-by-step and interactive execution mode. Here, I imagine selenese-runner to pause after each testcase step and waiting for user input from the stdin, e.g., enter, 'n', or literally any key. Each input trigger the next step and so on till the end of the test.

**Comment by tgianko** [comment]
fyi, I tried that my self [here](https://github.com/tgianko/selenese-runner-java/tree/newfeat/interactive). I will keep it there for a while for proper testing and later on I could do a pull request.

Feel free to share any comment about this feature.

**Comment by vmi** [comment]
Thanks for your PR!
I merged it.
