### ISSUE TITLE
Use existing Firefox instance?

### ISSUE THREAD

**Issue by Heliomance** [vmi/selenese-runner-java#215]
Is there any way to force Selenese Runner to use an already open instance of Firefox to run its script in? I'm needing to test some forms that are behind a login screen, and for various reasons automating login will be more trouble than it's worth. I'd like to be able to manually navigate to the starting page of the form, then set the test suite going from there, as you could do manually using the Selenium IDE plugin. Is that something that's possible?

**Comment by vmi** [comment]
I don't know how to use existing Firefox instance.

Workaround:

1. Create the test case which loops infinitely until logged in by using flow-control (*) commands. 

command             | target      | value
------------------- | ----------- | -----
open                | /login-page |
store               | false       | found
while               | ! ${found}  |
pause               | 1000        |
storeElementPresent | id=logout   | found
endWhile            |             |
(tests after        | logged      | in...)

2. Start the test case by Selenese Runner.

3. Do login operation manually.

(*) Selenese Runner supports the commands of the following Selenium IDE plugin.
https://github.com/davehunt/selenium-ide-flowcontrol
https://addons.mozilla.org/en-US/firefox/addon/flow-control/

**Comment by vmi** [comment]
Have you solved your problem?
If you have any additional questions, please reopen this issue.
