### ISSUE TITLE
Catch up Selenium 3.x

### ISSUE THREAD

**Issue by vmi** [vmi/selenese-runner-java#218]
Work in progress.

**Comment by tgianko** [comment]
hi @vmi, this is a good news indeed. When this may be available?  I am having [this](https://github.com/mozilla/geckodriver/issues/239) problem after the latest update of to FF 49 which apparently works with Selenium 3.0.0 only.

**Comment by vmi** [comment]
I released 3.0.0 which uses Selenium 3.x.

Note:
* To use Firefox you need `geckodriver`.
* New FirefoxDriver does not yet support mouse related features.
