### ISSUE TITLE
ClickAt command not taking parameters

### ISSUE THREAD

**Issue by amirjamak** [vmi/selenese-runner-java#221]
We have a test that uses clickAt command with some coordinates. After inspecting the report log we have seen that the command is ignoring the given parameters:
```
[2016-10-31 21:24:50.644 +01:00] [INFO] <4> Command#4: clickAt("css=#someId")
[2016-10-31 21:24:51.143 +01:00] [INFO] - [Success]
```
While similar command dragAndDrop is showing given coordinates:

```
[2016-10-31 21:24:56.523 +01:00] [INFO] <4> Command#4: dragAndDrop("css=#someId", "-50,1")
[2016-10-31 21:24:57.324 +01:00] [INFO] - [Success]
```

**Comment by amirjamak** [comment]
ありがとう ございました!

**Comment by amirjamak** [comment]
ありがとう ございました!

**Comment by amirjamak** [comment]
Can you please deploy 2.13.0 to maven central? 
https://mvnrepository.com/artifact/jp.vmi/selenese-runner-java
When can we expect it there? Thanks

**Comment by vmi** [comment]
Sorry, I didn't release 2.13.0 to maven central.
I released it.
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22jp.vmi%22%20AND%20a%3A%22selenese-runner-java%22

Note: This information doesn't synchronize with https://mvnrepository.com/artifact/jp.vmi/selenese-runner-java yet.
