### ISSUE TITLE
type Behaviour

### ISSUE THREAD

**Issue by Mendred** [vmi/selenese-runner-java#223]
Hello,

we're using Selenese 2.7.0 with Firefox v46.

The type command in 2.7.0 changed the value of the element and released the focus immeadiately causing the onChange-Event to be triggered. 

After upgrading to the latest version, we're facing some issues related to the 'type' behaviour. Type changes the value of an element, but does not release it anymore. OnChange is not triggered and our tests are failing. 

Do we have to change something in our test cases to get that working again or do we have to upgrade firefox? 

Best regards

Mendred

**Comment by vmi** [comment]
Hi,

I fixed the problem at 3.0.0 release.
Please test it.

Note: Since the version uses Selenium 3.x:
* To use Firefox you need `geckodriver`.
* New FirefoxDriver does not yet support mouse related features.

**Comment by vmi** [comment]
I closed this issue.
If your problem is not solved, please reopen it.
