### ISSUE TITLE
Error: Button not visible (style="display:none")

### ISSUE THREAD

**Issue by reegen** [vmi/selenese-runner-java#224]
Is there any way to force Selenese Runner to click a button that is not visible? I have a script of Selenium IDE where there is a button which style is "display:none":
<button id="lnkChoice" name="lnkChoice" class="" onclick="" style="display:none" type="submit">
I'm trying to use Selenese Runner to click this button, but I'm receiving this error: 
"Error: ElementNotVisibleException - Element is not currently visible and so may not be interacted with Command".
On the other hand, the script in Selenium IDE 2.9.1 is running perfectly well, and I intend do run it with Maven, using Selenese Runner as a plugin. Is it possible?

**Comment by vmi** [comment]
I fixed this problem and released new version.
Please test it.

**Comment by reegen** [comment]
Hi Motonori,

Thank you for the answer!

I will test it right shortly thereafter.

I only need a little bit more extra information, would you help me with
that?

Here's what's going on: I've just seen that the newest version of SRJ
(3.1.0) only supports Java 8 and later, am I right?

It occurs that I'm currently using Java version 1.7, Maven 3.3.9 e SRJ 2.3.

The relevant parts of my pom.xml are the following:












































*    <properties>
<exec.maven.plugin.version>1.5.0</exec.maven.plugin.version>
<selenese.runner.java.version>2.13.0</selenese.runner.java.version>
<speed>1000</speed>    </properties>    <dependencies>        <dependency>
<groupId>jp.vmi</groupId>
<artifactId>selenese-runner-java</artifactId>
<version>2.13.0</version>        </dependency>    </dependencies>
<build>        <plugins>            <plugin>
<groupId>org.codehaus.mojo</groupId>
<artifactId>exec-maven-plugin</artifactId>
<version>1.5.0</version>                <executions>
<execution>                        <id>Execution Tests Selenium</id>
                <phase>integration-test</phase>
<goals>                            <goal>exec</goal>
</goals>                        <configuration>
<executable>java</executable>
<includePluginDependencies>true</includePluginDependencies>

<includeProjectDependencies>true</includeProjectDependencies>
                <classpathScope>test</classpathScope>
        <longClasspath>true</longClasspath>
<commandlineArgs>                                                            <![CDATA[-cp
selenese-runner-java-2.13.0.jar jp.vmi.selenium.selenese.Main --driver
firefox --firefox c:/"Program Files (x86)"/"Mozilla Firefox"/firefox.exe
--remote-url http://v121d233:7003 <http://v121d233:7003> --set-speed 1000
--height 1080 --width 1920 src/test/selenium/TestSuite.html --html-result
target/selenium-reports]]>                            </commandlineArgs>
                    </configuration>                    </execution>
        </executions>            </plugin>        </plugins>    </build>*
Hereupon, my question is: would it possible for you to point the required
updates to my pom.xml to have my tests running ok?

By the way, will it be necessary to install manually the java 8, or a
simple update to my pom.xml should work it out?

Well, I really hope you can help me, since it won't bring you any
inconvenience.

Thanks in advance!

Best regards,

  Claudio ter Reegen.



2017-01-30 20:37 GMT-03:00 Motonori IWAMURO <notifications@github.com>:

**Comment by reegen** [comment]
Hi, 

I've already retested selenese-runner.jar version 3.1.0, using Java 8 (jdk1.8.0_121) and chrome browser, but I'm facing the same problem :(

Here's my command:
java -jar selenese-runner.jar 
--driver chrome 
--chromedriver c:/chromedriver/chromedriver.exe 
--remote-url http://v121d299:7003 
--set-speed 1000 
--height 1080 
--width 1920 
c:/mytests/TestSuite.html 
--html-result target/selenium-reports

And I'm getting this:
[2017-02-01 19:46:12.601 -03:00] [INFO] <3> Command#3: clickAndWait("id=lnkEscolha")
[2017-02-01 19:46:12.715 -03:00] [INFO] - [Success, but the element is not visible]

**Comment by vmi** [comment]
Hi,
Thank you for confirmation.

Since it is an informational message, there is no problem.
However, the message seems to confuse you, so I will change it.

**Comment by reegen** [comment]
Hi,

Sorry, I think I didn't explain very well.

The thing is, the act of clicking the hidden element causes an action.
And when I play the script using Selenium IDE, it works, but with selenese-runner-java it's not working.

I'll try to give you a better explanation tomorrow, with the whole scenario.

**Comment by vmi** [comment]
OK.
I am waiting for additional information.

Note: The following files are html and test case for this issue.
Please point out the incompleteness in the following files.

* HTML:
https://github.com/vmi/selenese-runner-java/blob/master/src/test/resources/htdocs/issue224.html
* Test case:
https://github.com/vmi/selenese-runner-java/blob/master/src/test/resources/selenese/testcase_issue224.html

**Comment by reegen** [comment]
Hi,
Sorry for my delay, it happened because I got this flu on the last few days, and I was terribly cold :(

First of all, let me show you the relevant part of the selenese code:
_**<tr>
	<td>type</td>
	<td>id=txtChoice</td>
	<td>TEXT</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>id=lnkChoice</td>
	<td></td>
</tr>**_

And the relevant part (the hidden button) of the html page follows below:
**_<button id="lnkChoice" name="lnkChoice" class="" onclick="" style="display:none" type="submit">
<span class="ui-button-text ui-c">ui-button</span></button>
<script id="lnkChoice_s" type="text/javascript">PrimeFaces.cw("CommandButton","widget_lnkChoice",{id:"lnkChoice",widgetVar:"widget_lnkChoice"});</script>_**

Which means that, the act of click the hidden button (id="lnkChoice") will trigger an action (javascript - primefaces), based on the option typed at the first element (id=txtChoice).

The action usually is to get us to another page (corresponding to the 'TEXT' option chosen), or show some error message (in case there's nothing that corresponds to the option chosen).

Finally, as I've said before, the selenese script above is running ok in Selenium IDE 2.9.1, but I'm not getting succeed in making it work in selenese-runner-java.

Tell me if the explanation above is suficiently understandable. In case it's not enough I can give you further information.

**Comment by reegen** [comment]
By the way, I did tests with the files you provided:
    HTML:
    https://github.com/vmi/selenese-runner-java/blob/master/src/test/resources/htdocs/issue224.html
    Test case:
    https://github.com/vmi/selenese-runner-java/blob/master/src/test/resources/selenese/testcase_issue224.html

And it's running fine. I still don't know why it doesn't run with that PrimeFaces script.

**Comment by reegen** [comment]
Sorry, I only show you the html form. But the code in jsf is like this:

![snippet3](https://cloud.githubusercontent.com/assets/16291629/22804307/38e2ca00-eef7-11e6-8055-ed445068436a.jpg)

And the function itself, in COMMANDER, is like this:

![snippet4](https://cloud.githubusercontent.com/assets/16291629/22804432/cf3f04fa-eef7-11e6-830a-1144b4dbd70e.jpg)

**Comment by vmi** [comment]
Hi,

In my code, when the click function of Selenium WebDriver API fails, it generate a **fake** click event with JavaScript. This feature is taken from the function of old style Selenium WebDriver.

I guess this **fake** click event may not mesh with the PrimeFaces event handler.

**Comment by vmi** [comment]
Please test the following operations and tell me the result.

1. Open the relevant page manually.
2. Run the following JavaScript code in the developer tools console.
```
document.getElementById('lnkChoice').click();
```
Is it works?

**Comment by reegen** [comment]
Yes, it worked!

**Comment by vmi** [comment]
I re-fixed the problem and released 3.2.0.
Please test it.

**Comment by reegen** [comment]
I've just finished my first test, and it's running OK! :)

**Comment by reegen** [comment]
I already succeded to download the version 3.2.0 of srj by updating my pom.xml. Thank you one more time!
