### ISSUE TITLE
Missing option for geckodriver

### ISSUE THREAD

**Issue by tortlepp** [vmi/selenese-runner-java#226]
Hi, since Selenium 3 you need [geckodriver](https://github.com/mozilla/geckodriver) to use Firefox in Selenium. To use it in selenese-runner-java you have to specify the path to geckodriver that way: `java.exe -Dwebdriver.gecko.driver=C:\Path\To\geckodriver.exe  -jar selenese-runner.jar ...`. In my opinion it would be more logic and convenient to have an option `--geckodriver` (similar to `--chromedriver`).

**Comment by vmi** [comment]
I added `--geckodriver` option and released 3.2.0.
Please test it.

**Comment by tortlepp** [comment]
Works great! Thanks a lot for the quick fix.
