### ISSUE TITLE
-- define option doesn't work with boolean values

### ISSUE THREAD

**Issue by falisco** [vmi/selenese-runner-java#236]
I'm using selenese-runner 3.3.0 from the command line and I want to bypass insecure certs using firefox, so I'm using it in the following way:

java -Dwebdriver.gecko.driver=[Path]\geckodriver64.exe -jar [Path]\selenese-runner.jar -d firefox --define acceptInsecureCerts=true [Path]\testcase.html" --html-result [Path]\tescase_result.html

I get the following result:

org.openqa.selenium.SessionNotCreatedException: InvalidArgumentError: Expected [object String] "true" to be boolean

I think that option --define is only working for String type capabilities, if I try to set an int capability like specificationLevel or a boolean capability like acceptInsecureCerts, I always get an error expecting a type different than String.

Thank you.

**Comment by vmi** [comment]
Hi,

I added a feature to specify the type for `--define` option, and released new version.

For example, specify as follows:
```
--define acceptInsecureCerts:bool=true
```

Please test it.

**Comment by vmi** [comment]
You can specify the following types:

* `str` (default)
* `int`
* `bool`

**Comment by falisco** [comment]
Hi,

I've tested it and it works like a charm.

Thank you very much for your work.

Regards.
