### ISSUE TITLE
Stale Element Problem

### ISSUE THREAD

**Issue by setiseta** [vmi/selenese-runner-java#237]
Hello,

I'm having troubles with stale element errors.
is there a option to retry / refresh the element handle on error within a period to get rid of these errors?

kind regards,
sebastian

**Comment by vmi** [comment]
Hi,
Sorry, there is currently no solution for your problem.
If you provide logs and/or test cases, I may be able to consider any solution.

**Comment by setiseta** [comment]
Its an internal test at the moment so its a bit hard to provide a rl example.
but maybe i can explain.
I'm testing a live search.
So i send some charakters to the search field.
and check the content / text of the first div in the result.
but if search is altered the div gets removed, and recreated with the new result.
and there i get the stale element exception.
i could wait a few seconds to get sure the result is here. but this will slow down test execution very hard.

any hint?

**Comment by vmi** [comment]
Hmmm,
Can I provide the error message and  Selenese Runner version?

**Comment by setiseta** [comment]
Version: Selenese Runner 3.3.0 (with Selenium 3.3.1)

Error (from HTML Report):

[Failure: stale element reference: element is not attached to the page document / (Session info: chrome=58.0.3029.81) / (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.10.8-200.fc25.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information) / Command duration or timeout: 27 milliseconds / For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html / Build info: version: '3.4.0', revision: 'unknown', time: 'unknown' / System info: host: 'd191812bbed3', ip: '172.17.0.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.8-200.fc25.x86_64', java.version: '1.8.0_121' / Driver info: org.openqa.selenium.chrome.ChromeDriver / Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5), userDataDir=/tmp/.org.chromium.Chromium.Yc9bfi}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.81, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}] / Session ID: 5258dc1cdff4ccc029333f16d2b50b8f / Command duration or timeout: 746 milliseconds]

**Comment by tortlepp** [comment]
Hi @setiseta , recently I had the same problem in a similar test case. Maybe you can try the `waitForElementPresent` command, in some cases it may help. But if the element is first removed and then added again, it is likely that there is no wait at all because the element is still present when `waitForElementPresent` is called. I did some research but did not find any nice solution and ended up in using the `pause` command when really necessary.

**Comment by setiseta** [comment]
Hi @tortlepp 
thank you for your reply.
what i wonder is, i have tried to do a WaitForVisible with XPath and new Text ( //div[text() = 'New Text'] ) but this also drops stale element exception.
I don't know why this is happening, cause the new text is never on the page bevor, so the driver / selenese should net get a element, and should not be able to get a stale element exception.

but yes if there is no other way, i need to do some pause. but this is not really beautifull, and if something slows down the loading it may fail, and testing is not really stable then.

**Comment by vmi** [comment]
Hi,
I released new version 3.4.0.
I think that I solved this problem.
But I have no test cases so I do not know if the problem really solved.

**Comment by setiseta** [comment]
Hi,
this sounds very nice. Thank you.
I will make some tests and give some feedback then.
It may take some days, to get good results.

Kind Regards,
Sebastian

**Comment by setiseta** [comment]
Hi,
i have done some tests.
it seems that the stale element error is gone on the "waitFor..." commands. so it works very well now.
i got one on a sendkey command and one on a click command, but this was on fast switching UI's, without waiting on anything for completion on switching.
so if the input which gets the keys from sendkeys is removed and reinserted while the command is running this exception occurs. but i think this is ok.
this was gone if i use set-speed=100 ( or i think if i fix the test and wait for completion of the ui switch befor executing the sendkey / klick command)
what you think?
i think it could be closed.

Thank you again this is very nice now.

Kind Regards,
Sebastian
