### ISSUE TITLE
Microsoft Edge Support?

### ISSUE THREAD

**Issue by morimt** [vmi/selenese-runner-java#266]
Hey,

is it possible to run tests in Microsoft Edge? On chrome etc. everything works fine but I can't get Edge running using selenese-runner.
I need to test mainly Edge because our customer uses it..
So, it is possible or will it be possible in the future?

Thanks

**Comment by vmi** [comment]
Hi,

I released 3.12.0.
I added Edge support, but I don't test it.
I think that EdgeDriver requires WebDriver binary.
https://docs.microsoft.com/en-us/microsoft-edge/webdriver
Please test it.

**Comment by morimt** [comment]
Hi,

thanks. My simple Tests are running through edge now. I will test further in the next few days. But till now it works fine!
