### ISSUE TITLE
new .side format

### ISSUE THREAD

**Issue by setiseta** [vmi/selenese-runner-java#267]
Hello,

are there any plans to support the .side format of the new selenium ide?
Its not that far for now, but it would be nice if selenese can run it in the future.

**Comment by vmi** [comment]
Hi,

Yes, there are. It is  work in progress.
Please wait for a while because I can not take much development time.

**Comment by leoforever** [comment]
I am also looking forward for this enhancement too. Hopefully it will deliver . Does it have a milestone?
Thanks a lot.

**Comment by vmi** [comment]
Hi,

I added `.side` support and released 3.15.0.
This is an experimental feature.
In a simple test, it works in Chrome, but it did not work in Firefox...

**Comment by leoforever** [comment]
I used command line to test .side script and it worked.
java -jar selenese-runner.jar --driver  chrome --chromedriver ./chromedriver ./test.side

But when I used java code to test  selenese, it failed. I pasted my code and exception.
My code:
		System.setProperty("webdriver.chrome.driver", "/home/wu/Desktop/test/chromedriver");
		WebDriver chromedriver = new ChromeDriver();
		
		Runner runner = new Runner();
		runner.setDriver(chromedriver);
		String scriptName = "/home/wu/Desktop/test/test.side";
		Selenese selenese = Parser.parse(scriptName, runner.getCommandFactory());
		CommandFactory cf = runner.getCommandFactory();

		TestCase testCase = (TestCase) selenese;
		Result result = runner.execute(testCase);
Exception：
Starting ChromeDriver 2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb) on port 27802
Only local connections are allowed.
May 28, 2018 11:22:11 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" java.lang.ClassCastException: jp.vmi.selenium.selenese.TestSuite$$EnhancerByGuice$$c1e1cd75 incompatible with jp.vmi.selenium.selenese.TestCase
	at MyTest.NewSelemium.playbackChrome(NewSelemium.java:64)
	at MyTest.NewSelemium.main(NewSelemium.java:117)

Chrome: Version 66.0.3359.170 (Official Build) (64-bit)
Selenium version: 3.1.2
Selenese version: 3.15.0

**Comment by vmi** [comment]
@leoforever ,

The parse result of `.side` file is a `TestSuite` including one or more `TestSuite` including one or more `TestCase`, not a `TestCase`.
(To access the `Selenese` element contained in `TestSuite`, use `TestSuite#getSeleneseList()`)
This is because one `.side` file contains multiple test suites.

**Comment by leoforever** [comment]
Yes, after I changed it to TestSuite, chrome worked and it also worked in Firefox. 
But you said  it works in Chrome, but it did not work in Firefox..., so I don't know why.
My firefox version is: 56.0.1
geckodriver 0.20.1

**Comment by vmi** [comment]
@leoforever,

I fixed bugs on Firefox.
Please test it.

**Comment by vmi** [comment]
I think that this problem was solved, so I closed this ticket.
If you still have problems, please reopen.
