### ISSUE TITLE
Make 3.14 avaible via maven

### ISSUE THREAD

**Issue by sez58** [vmi/selenese-runner-java#272]
Please make version 3.14.0 available via maven central repo.

**Comment by vmi** [comment]
Sorry!
I released it to maven repo.
Please wait a few hours.

**Comment by vmi** [comment]
I confirmed that it was released.

http://repo1.maven.org/maven2/jp/vmi/selenese-runner-java/3.14.0/
http://search.maven.org/#artifactdetails%7Cjp.vmi%7Cselenese-runner-java%7C3.14.0%7Cjar
