### ISSUE TITLE
Need Automatic Wait Command Line Option

### ISSUE THREAD

**Issue by sam-changtum** [vmi/selenese-runner-java#278]
Regarding ".side" formatted selenese scripts, and the "click" command for example (especially when AJAX is in play), I am experiencing differences in how Selenese Runner behaves versus how the new Selenium IDE behaves.

It appears the new Selenium IDE automatically "waits" for an element to be present before clicking an element. However, when the Selenese Runner runs the same script, it appears an automatic wait is not being performed.

The end result is a given script will succeed when run from the IDE but fail when run from the Runner.

I am wondering if a command line option is needed, which when set, would instruct the runner to match the new Selenium IDE's "automatic wait behavior".

**Comment by vmi** [comment]
Hi,

Sorry I'm late.
In the SIDE script, I changed it to wait until the timeout if the target element is not found.

I released 3.19.0, but I have not written the test code, so please try it.

**Comment by sam-changtum** [comment]
Hi,

I've downloaded 3.19 and it seems the click command from a SIDE script is timing out after 3 seconds. I do have a "--timeout 60000" setting on the command line. So currently, I think its not working because the click command is not respecting the command line's timeout setting.

**Comment by vmi** [comment]
Hmmm,

Can you provide a test case?

**Comment by sam-changtum** [comment]
Hi, thank you for your time on this item.

[Script for Selenese Runner Project.zip](https://github.com/vmi/selenese-runner-java/files/2488721/Script.for.Selenese.Runner.Project.zip)

When you run the attached "Script for Selenese Runner Project.side" script using the Selenium IDE it succeeds. However, when using the runner, it fails at "click" "css=p.mt-thank-you" with element not found error after a 3 second timeout. So the issue right now is probably the timeout needs to be longer. Currently I am not having any luck with controlling the timeout to make it wait longer; even when using the  "--timeout" command line argument.

**Comment by vmi** [comment]
Hi,

I re-fixed this problem and released 3.19.2.
Please test it.

**Comment by sam-changtum** [comment]
Hi, I have confirmed this issue is fixed. Thank you very much for your time on resolving this issue. Sorry for being so late at re-testing. Been a bit busy myself.

**Comment by sam-changtum** [comment]
Re-ran the test case and confirmed the issue is resolved.

**Comment by xiaospider** [comment]
Selenium IDE add **wait for**  commands after 3.4.0. https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.4.0

`Added new commands wait for element editable, wait for element not editable, wait for element present, wait for element not present, wait for element visible, wait for element not visible.`

@vmi Do selenese runner plan to support those command?  If I record .side with 3.4.0 IDE, Selenese throw exception now.

**Comment by vmi** [comment]
Hi, @xiaospider

> Do selenese runner plan to support those command?

I added these commands in 3.20.0.
Please test it.
