### ISSUE TITLE
private function to protected in Runner class

### ISSUE THREAD

**Issue by shenlian8** [vmi/selenese-runner-java#283]
I am using selenese-runner-java for Android and iOS native App test automation. 

I would like to extend the jp.vmi.selenium.selenese.Runner class instead of rewrite it. The private functions like getTakesScreenshot make it impossible to extend the class. It would be fine if the functions are protected.

As I am using appium java-client 6.1.0, would you please make the change from 3.16.0.

**Comment by vmi** [comment]
Hi,

I released 3.20.0.
I refined screenshot related methods and changed it to `protected`.
please check it.

**Comment by shenlian8** [comment]
Thanks!

I have tested in version 3.24.1. It works beside of one function.
Runner.setupMaxTimeTimer() should be public.


    /**
     * Setup MaxTimeActiveTimer.
     * @param maxTime the maxTime in milliseconds.
     */
    void setupMaxTimeTimer(long maxTime) {
        this.maxTimeTimer = new MaxTimeActiveTimer(maxTime);
    }
