### ISSUE TITLE
How to run .side file in proxy

### ISSUE THREAD

**Issue by Volley97** [vmi/selenese-runner-java#285]
There is a side file. You need to run it through a proxy. How to do it??
I tried this:
```
java -Dwebdriver.gecko.driver=/path_to_chromedriver -jar /path_to_selenese-runner.jar --proxy proxy.localhost:5555  /path_to_.side

```

**Comment by Volley97** [comment]
Mistake:
`jp.vmi.selenium.selenese.SeleneseRunnerRuntimeException: No such command: setWindowSize`
I remove the size of the window size in the side file and again displays an error that the command in the side file was not found on the site, which cannot be

**Comment by vmi** [comment]
Please re-open this issue if your problem is not resolved.
