### ISSUE TITLE
 Unknown locator type: linkText

### ISSUE THREAD

**Issue by xiaospider** [vmi/selenese-runner-java#287]
locator type: linkText is not supported.

Firefox 62.0.3
selenese-runner: 3.19.2
geckodriver : 0.23.0
selenium: 3.14.0

click("linkText=Products") => [Error: UnsupportedOperationException - Unknown locator type: linkText=Products (WebDriverElementFinder.findElementsInternal(WebDriverElementFinder.java:254) / WebDriverElementFinder.findElements(WebDriverElementFinder.java:294) / WebDriverElementFinder.findElements(WebDriverElementFinder.java:306) / WebDriverElementFinder.findElementWithTimeout(WebDriverElementFinder.java:379) / WebDriverElementFinder.findElementWithTimeout(WebDriverElementFinder.java:406) / Click.executeImpl(Click.java:31) / AbstractCommand.execute(AbstractCommand.java:155) / CommandList.doCommand(CommandList.java:86) / ScreenshotInterceptor.invoke(ScreenshotInterceptor.java:18) / AbstractDoCommandInterceptor.invoke(AbstractDoCommandInterceptor.java:29) / HighlightInterceptor.invoke(HighlightInterceptor.java:29) / AbstractDoCommandInterceptor.invoke(AbstractDoCommandInterceptor.java:29) / CommandLogInterceptor.invoke(CommandLogInterceptor.java:72) / AbstractDoCommandInterceptor.invoke(AbstractDoCommandInterceptor.java:29) / MaxTimeInterruptInterceptor.invoke(MaxTimeInterruptInterceptor.java:26) / AbstractDoCommandInterceptor.invoke(AbstractDoCommandInterceptor.java:29) / CommandList.execute(CommandList.java:134) / TestCase.execute(TestCase.java:213) / ExecuteTestCaseInterceptor.invoke(ExecuteTestCaseInterceptor.java:52) / AbstractExecuteTestCaseInterceptor.invoke(AbstractExecuteTestCaseInterceptor.java:29) / TestSuite.execute(TestSuite.java:185) / ExecuteTestSuiteInterceptor.invoke(ExecuteTestSuiteInterceptor.java:49) / AbstractExecuteTestSuiteInterceptor.invoke(AbstractExecuteTestSuiteInterceptor.java:29) / Runner.execute(Runner.java:707) / SeleniumScriptExecutor.playback(SeleniumScriptExecutor.java:164) / SeleniumScriptExecutorTest.testLocal(SeleniumScriptExecutorTest.java:64))]

**Comment by vmi** [comment]
Hi,

I added `linkText` locator support and released 3.20.0.
Please test it.

**Comment by xiaospider** [comment]
Tested, it's fixed.
