### ISSUE TITLE
empty command is not supported with selenese 3.20.0

### ISSUE THREAD

**Issue by JackJiaJJ** [vmi/selenese-runner-java#291]
flow control: command while is not supported

Firefox 60.4.0 ESR
selenese-runner: 3.20.0
geckodriver : 0.23.0
selenium: 3.14.59

I got below error:

"Error: InvalidSeleneseException - jp.vmi.selenium.selenese.SeleneseRunnerRuntimeException: No such command: "

**Comment by JackJiaJJ** [comment]
I tested flow control (if / else / end) which can work well

**Comment by vmi** [comment]
Hmmm, `while` command is supported.
My following test-case is passed:
https://github.com/vmi/selenese-runner-java/blob/master/src/test/resources/selenese/testcase_flowcontrol.side

Can you provide a minimal test-case?

**Comment by JackJiaJJ** [comment]
{
  "id": "aaf545e6-6140-45f8-82e6-1e144ffd3c3a",
  "version": "2.0",
  "name": "flow-control-while",
  "url": "http://www.bing.com",
  "tests": [{
    "id": "4f22cd74-c648-40f3-9801-34ab4dc32a05",
    "name": "flow-control-while",
    "commands": [{
      "id": "f89a2cb5-e9ac-471a-8024-a6ce1b46ad86",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "700e830a-df3a-4e02-985d-1d1c7aeaf133",
      "comment": "",
      "command": "executeScript",
      "target": "return 1",
      "targets": [],
      "value": "check"
    }, {
      "id": "88573887-bb5c-47e8-b052-2d121d345e9b",
      "comment": "",
      "command": "while",
      "target": "${check} < 3",
      "targets": [],
      "value": ""
    }, {
      "id": "212dd72c-d23b-494c-a6bc-7d345f5109bf",
      "comment": "",
      "command": "open",
      "target": "http://www.bing.com",
      "targets": [],
      "value": ""
    }, {
      "id": "8ae8a628-df9e-4da8-9929-2259b38c935f",
      "comment": "",
      "command": "executeScript",
      "target": "return ${check} + 1",
      "targets": [],
      "value": "check"
    }, {
      "id": "d81c2f9b-27bc-4330-99b8-354fdd89c5b4",
      "comment": "",
      "command": "end",
      "target": "",
      "targets": [],
      "value": ""
    }, {
      "id": "ea4e8c1b-a273-4544-9ae7-1e96adbf0542",
      "comment": "",
      "command": "click",
      "target": "id=sb_form_q",
      "targets": [
        ["id=sb_form_q", "id"],
        ["name=q", "name"],
        ["css=#sb_form_q", "css:finder"],
        ["xpath=//input[@id='sb_form_q']", "xpath:attributes"],
        ["xpath=//form[@id='sb_form']/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "e44df4dc-cc69-4469-877c-89593fa95abf",
      "comment": "",
      "command": "type",
      "target": "id=sb_form_q",
      "targets": [
        ["id=sb_form_q", "id"],
        ["name=q", "name"],
        ["css=#sb_form_q", "css:finder"],
        ["xpath=//input[@id='sb_form_q']", "xpath:attributes"],
        ["xpath=//form[@id='sb_form']/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "solaris"
    }, {
      "id": "acf2b925-c19d-4061-b5e5-d4c71aeade7f",
      "comment": "",
      "command": "sendKeys",
      "target": "id=sb_form_q",
      "targets": [
        ["id=sb_form_q", "id"],
        ["name=q", "name"],
        ["css=#sb_form_q", "css:finder"],
        ["xpath=//input[@id='sb_form_q']", "xpath:attributes"],
        ["xpath=//form[@id='sb_form']/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "${KEY_ENTER}"
    }, {
      "id": "42f89780-deff-43cc-a164-f0520ab9a04c",
      "comment": "",
      "command": "close",
      "target": "",
      "targets": [],
      "value": ""
    }, {
      "id": "83d729c2-11ef-447a-9b04-fa2f4e9313c1",
      "comment": "",
      "command": "",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "01765e46-fc53-47e0-aca1-fb69a4b1c1a6",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["4f22cd74-c648-40f3-9801-34ab4dc32a05"]
  }],
  "urls": ["http://www.bing.com/"],
  "plugins": []
}

**Comment by JackJiaJJ** [comment]
Above is my test case, I can playback it successfully on IDE

**Comment by vmi** [comment]
The command "id": "83d729c2-11ef-447a-9b04-fa2f4e9313c1" is empty.
I added the feature to treat empty command as `nop` command to 3.21.0.
Please test it.

**Comment by JackJiaJJ** [comment]
Thanks a lot ! I will test it

**Comment by JackJiaJJ** [comment]
I verified it with selenese 3.23.0
