### ISSUE TITLE
command "storeWindowHandle" is not supported with selenese 3.20.0

### ISSUE THREAD

**Issue by JackJiaJJ** [vmi/selenese-runner-java#292]
command "storeWindowHandle" is not supported which will affact the function of selecting the different window.

Firefox 60.4.0 ESR
selenese-runner: 3.20.0
geckodriver : 0.23.0
selenium: 3.14.59

This is part of my script:
![image](https://user-images.githubusercontent.com/39511725/53545717-57115480-3b65-11e9-99b1-e6f2f6739a1d.png)

I got below error:

Error: InvalidSeleneseException - jp.vmi.selenium.selenese.SeleneseRunnerRuntimeException: No such command: storeWindowHandle

**Comment by vmi** [comment]
I added `storeWindowHandle` command and `handle=` parameter with `selectWindow` command, and released 3.21.0.
Please test it.

**Comment by JackJiaJJ** [comment]
Thanks a lot ! I will test it

**Comment by JackJiaJJ** [comment]
I verified it with selenese 3.23.0
