### ISSUE TITLE
different results in Selenium IDE and runner

### ISSUE THREAD

**Issue by yj0930** [vmi/selenese-runner-java#298]
assume a web page (https://www.google.com) without an input element named "qq", in Selenium IDE:

store xpath count | xpath=//input[@name='qq'] | q2
assert | q2 | 0

will pass, but failed in runner, the error message:

Failure: Element xpath=//input[@name='qq'] not found

**Comment by vmi** [comment]
Thank you for your report.

I fixed this problem and released 3.23.0.
Please test it.

**Comment by yj0930** [comment]
It worked, thanks.
