### ISSUE TITLE
System proxy does not support method setNoProxy 

### ISSUE THREAD

**Issue by leoforever** [vmi/selenese-runner-java#303]
When I using system proxy and set no proxy, it throws exception.
proxy.setProxyType(ProxyType.SYSTEM);
proxy.setNoProxy(noProxiesOn);

 And I check the source code, find that setNoProxy  is for MANUAL proxy only. Is there any reason and can we add set no proxy for other type of proxy(system proxy and pac proxy)

public Proxy setNoProxy(String noProxy) {
verifyProxyTypeCompatibility(ProxyType.MANUAL);
this.proxyType = ProxyType.MANUAL;
this.noProxy = noProxy;
return this;
}

**Comment by vmi** [comment]
Hi,

I have released 3.25.0 with `--proxy-type` option. (supporting parameters `manual`, `pac`, `autodetect`, and `system`)
However, I have not been able to test any settings other than `manual`.
I hope you can test it.

**Comment by leoforever** [comment]
Actually I means the setNoProxy has some issue.
For example.
I set the proxy type is System proxy, and then setNoProxy (www.google.com), then I visit www.google.com will not use the proxy.
And I find the code is actually in selenium. I will open the issue in selenium and close this issue.
