### ISSUE TITLE
 The log recorder of TestCase is already set.

### ISSUE THREAD

**Issue by shenlian8** [vmi/selenese-runner-java#308]
Hi, 

If the same test case is used twice in test suit, I get the error:

 The log recorder of TestCase[<test case name>] (<path of test case>) is already set.

Then the test suit will be brocken.

I have used with version 3.17. It was no problem. I just want to update to version 3.26 and I have that problem and cannot finish the test.

Would you please take a look. Thanks!

Lian Shen

**Comment by shenlian8** [comment]
I have tested. It is from 2.25. It works in 3.24.1

**Comment by vmi** [comment]
I fixed this problem and released 3.27.0.
Please test it.

**Comment by shenlian8** [comment]
Yes. I can confirm that the issue was fixed in version 3.27.0

Thanks!
