### ISSUE TITLE
Runner.setupMaxTimeTimer() should be public

### ISSUE THREAD

**Issue by shenlian8** [vmi/selenese-runner-java#309]
Hi,

the access modifier of  function Runner.setupMaxTimeTimer() is default.

    /**
     * Setup MaxTimeActiveTimer.
     * @param maxTime the maxTime in milliseconds.
     */
    void setupMaxTimeTimer(long maxTime) {
        this.maxTimeTimer = new MaxTimeActiveTimer(maxTime);
    }

As I am using this function in another package would you please change this function in public, like other functions.

It should be nice if you can make the change from 3.24.

Thanks!

Lian

**Comment by vmi** [comment]
Hi,

I made `Runner#setupMaxTimeTimer()` public,
and released 3.27.1.
Please check it.

**Comment by shenlian8** [comment]
Yes it works. Thanks!
