### ISSUE TITLE
WebdriverElementFinder.findElementsByLocator() causes endless loop

### ISSUE THREAD

**Issue by shenlian8** [vmi/selenese-runner-java#311]
Hi,

I try to find a legal but not exists xpath eg. //foo under a chrome driver. 

In WebdriverElementFinder.pushFrame
driver.switchTo().frame(0) is called. In some cases (but I do not know which case) chrome driver do not switch the frame. It stays in the main html. This should be the bug of chrome driver. In this case, the WebdriverElementFinder.findElementsByLocator() function will go into an endless loop. 

Would you add one check in pushFrame() function that checks if the frame is really be switched. If it is not switched, then the findElementsByLocator() should return null to prevent the endless loop.

This is not a bug from your side. It is caused by chrome driver. 

Thanks!

Lian Shen

**Comment by shenlian8** [comment]
Issue report on chrome driver

https://bugs.chromium.org/p/chromedriver/issues/detail?id=3232&q=&colspec=ID%20Status%20Pri%20Owner%20Summary

Issue report on selenium

https://github.com/SeleniumHQ/selenium/issues/5401

**Comment by vmi** [comment]
Hi,

I have added a nested frame depth limit (max depth is 16) because Selenium does not provide getting frame information.
I released 3.29.0.
Please test it.

**Comment by vmi** [comment]
Please re-open this issue if there is anything that Selenese Runner Java can do about it.
