### ISSUE TITLE
SelectFrame in case screenshot-all

### ISSUE THREAD

**Issue by shenlian8** [vmi/selenese-runner-java#315]
Hi,

if **screenshot-all** is set to true and **selectFrame** is used.

After **selectFrame** in **takeScreenshot** function in **Runner** class, it is called this.driver.switchTo().defaultContent();

So I think in **selectFrame**, the 
public boolean mayUpdateScreen() {
        return false;
    }
must be set.

What do you think?

Lian

**Comment by vmi** [comment]
Hi,

I fixed this problem and  and released 3.29.0.
Please test it.

**Comment by vmi** [comment]
Please re-open this issue if your problem is not resolved.
