### ISSUE TITLE
Selenese enters infinite loop when using "run" command

### ISSUE THREAD

**Issue by billxiao** [vmi/selenese-runner-java#320]
Hi,

When I run the attached simple SIDE file, Selenese-runner-java would enter infinite loop. The SIDE file is actually very simple, only containing a "run" command which calls another simple test case.

I believe this is a bug. Please have a look.

The command line I used to run the SIDE is like the following:
java -jar selenese-runner.jar --driver chrome --max-retries=3 D:\asd.side

[asd.zip](https://github.com/vmi/selenese-runner-java/files/5039644/asd.zip)

**Comment by billxiao** [comment]
Finally I spot the bug. It's the "run" command where the retry times in the context is reset by its sub test case. So "run" command will never reach max retries and be locked in an infinite loop.

My solution is to never retry "run" command and once return from the execution of sub test case, set the retries in the context to be max to let it break out of the while loop.

**Comment by vmi** [comment]
Sorry for being late.
I have released version 3.32.0 that fixes this problem.
Please check it.

**Comment by vmi** [comment]
Please re-open this issue if your problem is not resolved.
