### ISSUE TITLE
Do we need to driver.switchTo().defaultContent(); before take screenshot?

### ISSUE THREAD

**Issue by shenlian8** [vmi/selenese-runner-java#321]
Hi,

I'd like to ask, in Runner class, do we need in takeScreenshot(File file, boolean entirePage) methode the block any more?

        try {
            // cf. http://prospire-developers.blogspot.jp/2013/12/selenium-webdriver-tips.html (Japanese)
            driver.switchTo().defaultContent();
        } catch (Exception e) {
            // some times switching to default context throws exceptions like:
            // Method threw 'org.openqa.selenium.UnhandledAlertException' exception.
        }
Thanks!

Best regards

Lian

**Comment by vmi** [comment]
I think it's no longer needed because the screenshot feature was replaced by Selenium Shutterbug.

**Comment by shenlian8** [comment]
Can you please remove it? 
Because the appium server hat bug from 1.16 with driver.switchTo().defaultContent();
If nativ app is under testing this cause a wait time for 60 seconds.

**Comment by vmi** [comment]
Hi,

I fixed and released it.
Please check new version.

**Comment by shenlian8** [comment]
Hi,

it works. Thanks a lot!

Best regards

Lian
