### ISSUE TITLE
waitFor* commands should result in an error, not a warning

### ISSUE THREAD

**Issue by blutorange** [vmi/selenese-runner-java#330]
WaitFor* command currently only result in a warning (https://github.com/vmi/selenese-runner-java/blob/master/src/main/java/jp/vmi/selenium/selenese/command/Assertion.java#L145). With Selenium IDE, they result in an error:

![image](https://user-images.githubusercontent.com/2456413/132372335-c3dded16-fa77-442f-844d-0d107140dfe8.png)

When these commands fail, they usually represent a test failure (element not present that was expected etc.). I'm using the this library programatically to integrate side tests in JUnit. When these commands only result in a warning, the test does not fail as it should. As a workaround, I'm now checking whether the result message contains the text "Assertion failed".

Can this be changed to an error?

**Comment by shenlian8** [comment]
It is right to return warning.

If you need you can use assert... commands.

You can also conbine them.

Wait... and then
Assert...

This give you more possibilities.

Andre Wachsmuth ***@***.***> 于 2021年9月7日周二 17:40写道：

**Comment by blutorange** [comment]
Well, the problem is there's not "Assert element not visible" command, only a "Wait for element not visible command" in Selenium IDE.

**Comment by shenlian8** [comment]
Just some expierence.

Not visible is always not save.

Andre Wachsmuth ***@***.***> 于 2021年9月7日周二 18:37写道：

**Comment by vmi** [comment]
I'm sorry for the delay.

I will fix it, so please wait for a while.

> I'm not sure about the precise goals of this project, should it mimic the behavior of Selenium IDE?

The goal of this project is to mimic Selenium IDE as accurately as possible.
(this is limited to what can be implemented with the functions provided by WebDriver)

Note that the current behavior is due to the fact that we are following the **legacy** Selenium IDE.

**Comment by blutorange** [comment]
@vmi No problem, take your time, it's not urgent. For the time being I'm using using my own runner implementation for now so I can check which command failed and act accordingly. 

As far as I know over at Selenium IDE they started rewriting it as an electron app with native WebDriver support to overcome some of the issues with it being a browser plugin, but it seems that project has a long way to go. Though that would probably be easier to mimic.

**Comment by vmi** [comment]
Thank you very much for your patience.
I have released version 4.0.0 that fixes this problem.
Please check it out.

**Comment by blutorange** [comment]
No problem, thanks for the fix and the release. I checked it out, works as I would have expected it : )
